#!/bin/bash

# This script will build and then run the entire parking project

# Replace with your own Duckiebot's name!
export BOTNAME=manipanpan

docker -H "$BOTNAME".local build --no-cache -t proj-parking:v1 .

docker -H "$BOTNAME".local run -it --rm -v /data:/data --privileged --network=host proj-parking:v1
