#!/bin/bash

# This script runs the parking project without rebuilding the project

# Replace with your own Duckiebot's name!
export BOTNAME=manipanpan

docker -H "$BOTNAME".local run -it --rm -v /data:/data --privileged --network=host proj-parking:v1
