#!/bin/bash

# This starts the demos which are needed for lane following (and hence, also for parking) to work

# Replace with your own Duckiebot's name!
export BOTNAME=manipanpan

dts duckiebot demo --demo_name all_drivers --duckiebot_name $BOTNAME --package_name duckiebot_interface --image duckietown/dt-duckiebot-interface:daffy

sleep 10

dts duckiebot demo --demo_name all --duckiebot_name $BOTNAME --package_name car_interface --image duckietown/dt-car-interface:daffy
